### ISSUE TITLE
Bug when zooming small image

### ISSUE THREAD

**Issue by Sol88** [suzuki-0000/SKPhotoBrowser#68]
Hi! First of all thanks for such control!

There is a bug when trying to zoom a small image with double tap
If you try to zoom such image with gesture everything is fine (it just not scale)

Here is an example
![simulator screen shot 30 2016 16 37 07](https://cloud.githubusercontent.com/assets/5029909/14144312/3e1a80c6-f6a0-11e5-8f42-e203478d0171.png)
![simulator screen shot 30 2016 16 37 12](https://cloud.githubusercontent.com/assets/5029909/14144318/43cdcffa-f6a0-11e5-8ec6-a4e88e28f424.png)

**Comment by alexsanderkhitev** [comment]
Hello @Sol88 
Thank you for your report. I didn't know about this bug.

**Comment by alexsanderkhitev** [comment]
Hello @Sol88 
What do you use image size when you get this bug? Because I tried 450 * 450, 300 * 300 pixels and I didn't get this bug.

**Comment by alexsanderkhitev** [comment]
@Sol88 
I found this size it is 320 * 240

**Comment by alexsanderkhitev** [comment]
@Sol88 
I fixed this problem. Please you should to update your pods on the 1.7.8 version. Please, write if I could to fix this bug or not. I simulated this mistake and my changes fixed it. If those changes resolved your problem please, you to close this issue.
https://www.dropbox.com/s/m316ai4ycavlc45/IMG_1781.PNG?dl=0

**Comment by Sol88** [comment]
@alexsanderkhitev Hi! 
Sorry for delay, but unfortunately I'm still getting this bug
I'm getting this bug when downloading small image from the internet. I'm getting this bug not only on iPhone 5, but on iPhone 6 too.

so here is this small image
https://www.dropbox.com/s/p2mx4rr0o7hbamd/gallery_photo%401x.png?dl=0

and here is the video showing this bug
https://www.dropbox.com/s/yzmj48b1pdiw7u7/PhotoBrowser.mov?dl=0

**Comment by alexsanderkhitev** [comment]
@Sol88 Hello! I reopened this issue! I thought I fixed this bug because I checked framework by may small images.

**Comment by Sol88** [comment]
@alexsanderkhitev 
Ok, if I'll fix this bug I'll write here

**Comment by alexsanderkhitev** [comment]
@Sol88 I think that I could to fix this problem. Please, update your pods and give feedback

**Comment by alexsanderkhitev** [comment]
@Sol88 I checked with your image.

**Comment by Sol88** [comment]
@alexsanderkhitev 
yes, now it works like a charm!
thanks a lot!

**Comment by alexsanderkhitev** [comment]
@Sol88 I am very happy)
